name: namaz_vakti
description: "Fasting Application for Muslims All around the world."
publish_to: 'none'
version: 1.0.1+2 

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  geolocator: ^13.0.3
  provider: ^6.0.5
  localization: ^2.1.1
  shared_preferences: ^2.2.2
  home_widget: ^0.7.0+1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/languages/
    - assets/images/
  uses-material-design: true
