name: fastingapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  localization: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/languages/
  uses-material-design: true
